version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydrive
    volumes:
      - /path/to/data:/data/
      - /path/to/temp:/temp/
    ports:
      - "${HTTP_PORT:-3000}:3000"
      - "${HTTPS_PORT:-8080}:8080"
    env_file:
      - .env # Copy .env.example to .env.development or .env and fill in the values