version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/config/.env.development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - ${FS_DIRECTORY}:/data
    ports:
      - "3000:3000"
      - "8080:8080"
      - "5173:5173"
    environment:
      - DOCKER=true
