version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/config/.env.development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - ${FS_DIRECTORY}:/data
    ports:
      - "${HTTP_PORT:-3000}:3000"
      - "${HTTPS_PORT:-8080}:8080"
      - "5173:5173"
    environment:
      - DOCKER=true
